# Generated by Django 4.0.4 on 2022-05-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_created_alter_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
    ]
