# Generated by Django 4.0.4 on 2022-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='tite',
        ),
    ]
