# Generated by Django 4.0.4 on 2022-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='blogs',
        ),
    ]
