# Generated by Django 4.0.4 on 2022-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blog_owner_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
