# Generated by Django 4.0.4 on 2022-05-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_blog_created_alter_message_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
    ]
